server:
  port: 8080

spring:
  application:
    name: "agenda-aulas-api"

  datasource:
    url: jdbc:postgresql://localhost:5432/schedule
    username: postgres
    password: 1209

  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    clean-disabled: false

jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key

logging:
  level:
    org:
      flywaydb: DEBUG
    springframework:
      security: DEBUG
